# Generated by Django 3.0.8 on 2020-08-22 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_book', '0006_remove_notificationread_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date(2020, 8, 22))),
            ],
            options={
                'verbose_name': 'Общесистемная нотификация',
                'verbose_name_plural': 'Общесистемные нотификации',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 22)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 22)),
        ),
        migrations.CreateModel(
            name='SystemNotificationRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.SystemNotification')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='users_read',
            field=models.ManyToManyField(through='app_book.SystemNotificationRead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PersonalNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date(2020, 8, 22))),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персональная нотификация',
                'verbose_name_plural': 'Персональные нотификации',
            },
        ),
    ]
