# Generated by Django 3.0.8 on 2020-08-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0007_auto_20200822_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationread',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notificationread',
            name='users',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationRead',
        ),
    ]
