# Generated by Django 3.0.8 on 2020-08-22 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0008_auto_20200822_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemnotificationread',
            options={'verbose_name': 'Прочитанная общесистемная нотификация', 'verbose_name_plural': 'Прочитанные общесистемные нотификации'},
        ),
        migrations.AlterField(
            model_name='personalnotification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 22, 16, 56, 27, 12031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 22, 16, 56, 27, 12031, tzinfo=utc)),
        ),
    ]
